export const conf = {
  APPWRITE_PROJECT_ID: String(process.env.APPWRITE_PROJECT_ID),
  APPWRITE_URL: String(process.env.APPWRITE_URL),
  APPWRITE_BUCKET_ID: String(process.env.APPWRITE_BUCKET_ID),
  SMTP_SERVER_USERNAME: String(process.env.SMTP_SERVER_USERNAME),
  SMTP_SERVER_PASSWORD: String(process.env.SMTP_SERVER_PASSWORD),
  SITE_MAIL_RECIEVER: String(process.env.SITE_MAIL_RECIEVER),
};
