export const conf = {
  NEXT_PUBLIC_APPWRITE_PROJECT_ID: String(
    process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID
  ),
  NEXT_PUBLIC_APPWRITE_URL: String(process.env.NEXT_PUBLIC_APPWRITE_URL),
  NEXT_PUBLIC_APPWRITE_BUCKET_ID: String(
    process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID
  ),
  NEXT_PUBLIC_APPWRITE_DATABASE_ID: String(
    process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID
  ),
  NEXT_PUBLIC_APPWRITE_GALLERY_COLLECTION_ID: String(
    process.env.NEXT_PUBLIC_APPWRITE_GALLERY_COLLECTION_ID
  ),
  NEXT_PUBLIC_SMTP_SERVER_USERNAME: String(
    process.env.NEXT_PUBLIC_SMTP_SERVER_USERNAME
  ),
  NEXT_PUBLIC_SMTP_SERVER_PASSWORD: String(
    process.env.NEXT_PUBLIC_SMTP_SERVER_PASSWORD
  ),
  NEXT_PUBLIC_SITE_MAIL_RECIEVER: String(
    process.env.NEXT_PUBLIC_SITE_MAIL_RECIEVER
  ),
};
